version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
#    ports:
#      - "12345:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      

  db:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
#    ports:
#      - "3308:3306"
    restart: on-failure


  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
