# Generated by Django 5.0.6 on 2024-05-22 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_auto_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='capacity',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.FloatField(default=2.0, validators=[django.core.validators.MinLengthValidator(0.5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
