# Generated by Django 5.0.6 on 2024-05-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carmodel_body_type_carmodel_capacity_carmodel_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.FloatField(),
        ),
    ]
