# Generated by Django 5.0.6 on 2024-06-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatars'),
            preserve_default=False,
        ),
    ]
